ARG version
FROM almalinux:${version:-9}
ARG course="DevOps with AWS" \
    trainer="sivakumar Reddy" \
    duration="120 hrs"
ENV duration=$duration
RUN echo "COurse: $course, Trainer: $trainer, Duration: $duration"
CMD ["sleep", "100"]

